routes/web.php
                Route::post('upload','Finance\DebtPaymentSOController@upload')->name('upload');
                Route::delete('upload','Finance\DebtPaymentSOController@upload')->name('upload');
                
                Route::resource('', 'Finance\DebtPaymentSOController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
        });
    
        /**
        * Transaction
        * */ 
        Route::name('transaction.')->prefix('transaction')->group(function () {
            Route::name('purchase.order.')->prefix('purchase-order')->group(function(){
                Route::post('upload','Transaction\PurchaseOrderController@upload')->name('upload');
                Route::delete('upload','Transaction\PurchaseOrderController@upload')->name('upload');
                
                Route::resource('', 'Transaction\PurchaseOrderController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('retur.purchase.order.')->prefix('retur-purchase-order')
            ->group(function(){
                Route::post('upload','Transaction\ReturPurchaseOrderController@upload')
                    ->name('upload');
                Route::delete('upload','Transaction\ReturPurchaseOrderController@upload')
                    ->name('upload');
                
                Route::resource('', 'Transaction\ReturPurchaseOrderController',[
                    'parameters' => [
                        '' => 'id',
                    ]
                ])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('sales.order.')->prefix('sales-order')->group(function(){
                Route::post('upload','Transaction\SalesOrderController@upload')->name('upload');
                Route::delete('upload','Transaction\SalesOrderController@upload')->name('upload');
                Route::any('{id}/print-small','Transaction\SalesOrderController@printSmall')->name('note.small');
                
                Route::resource('', 'Transaction\SalesOrderController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('retur.sales.order.')->prefix('retur-sales-order')
            ->group(function(){
                Route::post('upload','Transaction\ReturSalesOrderController@upload')
                    ->name('upload');
                Route::delete('upload','Transaction\ReturSalesOrderController@upload')
                    ->name('upload');
                
                Route::resource('', 'Transaction\ReturSalesOrderController',[
                    'parameters' => [
                        '' => 'id',
                    ]
                ])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('mutation.product.')->prefix('mutation-product')->group(function(){
                Route::post('upload','Transaction\MutationProductController@upload')->name('upload');
                Route::delete('upload','Transaction\MutationProductController@upload')->name('upload');
                
                Route::resource('', 'Transaction\MutationProductController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('stock.opname.')->prefix('stock-opname')->group(function(){
                Route::post('upload','Transaction\StockOpnameController@upload')->name('upload');
                Route::delete('upload','Transaction\StockOpnameController@upload')->name('upload');
                Route::get('processed/{id}','Transaction\StockOpnameController@change_waiting')->name('change.waiting');
                Route::get('verified/{id}','Transaction\StockOpnameController@change_process')->name('change.process');
                Route::get('revert-verified/{id}','Transaction\StockOpnameController@revert_verified')->name('revert.verified');
                Route::any('print/{id}','Transaction\StockOpnameController@print')->name('print');
                Route::get('form-verfied/{id}','Transaction\StockOpnameController@form_verified')->name('form.verified');
                
                Route::resource('', 'Transaction\StockOpnameController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });

            Route::name('pulse.')->prefix('pulse')->group(function(){
                Route::resource('', 'Transaction\PulseController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
        });
    
        /**
        * Log
        * */ 
        Route::name('log.')->prefix('log')->group(function () {
            Route::resource('log-history','Log\LogHistoryController')->only([
                'index'
            ])->names('log.history');
    
            Route::resource('log-bank-transaction','Log\LogBankTransactionController')->only([
                'index'
            ])->names('log.bank.transaction');
    
            Route::resource('log-stock-transaction','Log\LogStockTransactionController')->only([
                'index'
            ])->names('log.stock.transaction');
        });
    
        /**
        * Report
        * */ 
        Route::name('report.')->prefix('report')->group(function () {
            Route::any('stock','Report\StockController@index')->name('stock.index');
            Route::any('product-identity','Report\ProductIdentityController@index')->name('product.identity.index');
            Route::any('sales-order','Report\SalesOrderController@index')->name('sales.order.index');
            Route::any('purchase-order','Report\PurchaseOrderController@index')->name('purchase.order.index');
            Route::any('expend-all','Report\ExpendAllController@index')->name('expend.all.index');
            Route::any('income-all','Report\IncomeAllController@index')->name('income.all.index');
            Route::any('financial-statement','Report\FinanceStatementController@index')->name('financial.statement.index');
            Route::any('loss-profit','Report\LossProfitController@index')->name('loss.profit.index');
            Route::any('supplier-tax','Report\SupplierTaxController@index')->name('supplier.tax.index');
            Route::any('income-expend','Report\IncomeExpendController@index')->name('income.expend.index');
        });
    });

    Route::name('setting.user.')->prefix('setting/user')->group(function () {
        Route::any('profile','Setting\UserController@profile')->name('profile');
        Route::post('upload','Setting\UserController@upload')->name('upload');
        Route::delete('upload','Setting\UserController@upload')->name('upload');
    });
    
    /**
    * User Permission
    * */
    Route::get('/js/permission.js', function () {
        $has_permissions = \Session::get('permission');
        $has_permissions = $has_permissions->pluck('id', 'slug')->toArray();
        header('Content-Type: text/javascript');
        echo('window.posp = ' . json_encode($has_permissions) . ';');
        exit();
    })->name('assets.permission');

    /**
    * Localization
    * */
    Route::get('/js/lang.js', function () {
        if (config('app.env') == 'local' || config('app.env') == 'development') {
            $lang = \Session::get('language');
    
            $files   = glob(resource_path('lang/' . $lang . '/*.php'));
            $strings = [];

            foreach ($files as $file) {
                $name           = basename($file, '.php');
                $strings[$name] = require $file;
            }
        } else {
            $strings = Cache::rememberForever('lang.js', function () {
                $lang = \Session::get('language');
    
                $files   = glob(resource_path('lang/' . $lang . '/*.php'));
                $strings = [];
    
                foreach ($files as $file) {
                    $name           = basename($file, '.php');
                    $strings[$name] = require $file;
                }
    
                return $strings;
            });
        }

        header('Content-Type: text/javascript');
        echo('window.i18n = ' . json_encode($strings) . ';');
        exit();
    })->name('assets.lang');

    Route::name('ajax.')->prefix('ajax')->group(function(){
        Route::get('list-product','Master\ProductController@ajaxListProduct')->name('list.product');
        Route::get('list-product-identity/{id?}','Master\ProductController@product_identity')->name('list.product.identity');
        Route::get('list-product-po/{id?}','Transaction\PurchaseOrderController@ajaxDetailPO')->name('list.product.po');
        Route::get('list-product-so/{id?}','Transaction\SalesOrderController@ajaxDetailSO')->name('list.product.so');
        Route::get('list-product-sop/{id?}','Transaction\StockOpnameController@ajaxDetailSOP')->name('list.product.so');
        Route::get('category','Master\CategoryController@ajaxCategory')->name('category');
        Route::get('brand','Master\BrandController@ajaxBrand')->name('brand');
        Route::get('product','Master\ProductController@ajaxProduct')->name('product');

app/Http/Controllers/Report/ExpendAllController.php
<?php

namespace App\Http\Controllers\Report;

use App\Models\DebtPaymentPurchaseOrder;
use App\Util\Base\CoreController;
use App\Models\ReturSalesOrder;
use App\Models\CategoryExpend;
use App\Models\PurchaseOrder;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\Incentive;
use App\Models\Expend;
use App\Models\Branch;
use App\Models\Bank;
use Excel;

class ExpendAllController extends CoreController
{
    public function index()
    {
        if( request('ex') ) {
            return $this->exportExcel();
        }

        $categoryExp = CategoryExpend::active()->get()->pluck('name','id');
        $branchs = Branch::active()->get()->pluck('name','id');

        return Layout::render('report.expend_all.index', [
            'categoryExp' => $categoryExp,
            'branchs' => $branchs
        ]);
    }

    public function exportExcel()
    {
        $q_po = PurchaseOrder::with('bank', 'details', 'details.productIdentity', 'details.product');
        $q_dpo = DebtPaymentPurchaseOrder::with('bank');
        $q_rso = ReturSalesOrder::with('bank');
        $q_incentiveDecrease = Incentive::with('bank')->decrease();
        $q_exp = Expend::with('bank');

        if( request('_dt') )
        {
            $date = Util::get('_dt');
            $date = explode(" - ", $date);
            
            $q_po->whereBetween('date', $date);
            $q_dpo->whereBetween('date', $date);
            $q_rso->whereBetween('date', $date);
            $q_incentiveDecrease->whereBetween('date_transaction', $date);
            $q_exp->whereBetween('expend_date', $date);
        }

        if( request('_bc') )
        {
            $branch_id = Util::get('_bc');

            $q_po->whereBranchId($branch_id);
            $q_dpo->whereHas('purchaseOrder', function($q) use($branch_id) {
                $q->whereBranchId($branch_id);
            });
            $q_rso->whereBranchId($branch_id);
            $q_incentiveDecrease->whereBranchId($branch_id);
            $q_exp->whereBranchId($branch_id);
        }

        if( request('_bk') || !empty(config('default.bank_id')) )
        {
            $bank_id = !empty(config('default.bank_id')) ? config('default.bank_id') : Util::get('_bk');
            
            $q_po->where('bank_id', $bank_id);
            $q_dpo->where('bank_id', $bank_id);
            $q_rso->where('bank_id', $bank_id);
            $q_incentiveDecrease->where('bank_id', $bank_id);
            $q_exp->where('bank_id', $bank_id);
        }

        if( request('_cexp') ) {
            $category_expend_id = Util::get('_cexp');
            $q_exp->where('category_expend_id', $category_expend_id);
        }

        $purchase_order = collect([]);
        $debtPaymentPo = collect([]);
        $returSO = collect([]);
        $incentiveExpend = collect([]);
        $expend = collect([]);
        $total_dppo = 0;
        $total_rso = 0;
        $total_po = 0;
        $total_incentive_expend = 0;
        $total_expend = 0;
        $expend_type = trans('global.all');
        if (request('_et')) {
            $expend_type = trans('expend_all.list.expend_type.' . Util::get('_et'));
            switch (Util::get('_et')) {
                case 1:
                    $purchase_order = $q_po->get();
                    $total_po = $purchase_order->sum('paid_off');
                    break;
                
                case 2:
                    $debtPaymentPo = $q_dpo->get();
                    $total_dppo = $debtPaymentPo->sum('paid');
                    break;
                
                case 3:
                    $returSO = $q_rso->get();
                    $total_rso = $returSO ->sum('total_amount');
                    break;

                case 4:
                    $incentiveExpend = $q_incentiveDecrease->get();
                    $total_incentive_expend = $incentiveExpend->sum('amount');
                    break;

                case 5:
                    $expend = $q_exp->get();
                    $total_expend = $expend->sum('amount');
                    break;

                default:
                    # code...
                    break;
            }
        } else {
            $purchase_order = $q_po->get();
            $debtPaymentPo = $q_dpo->get();
            $returSO = $q_rso->get();
            $incentiveExpend = $q_incentiveDecrease->get();
            $expend = $q_exp->get();

            $total_po = $purchase_order->sum('paid_off');
            $total_dppo = $debtPaymentPo->sum('paid');
            $total_rso = $returSO ->sum('total_amount');
            $total_incentive_expend = $incentiveExpend->sum('amount');
            $total_expend = $expend->sum('amount');
        }

        $total_expend_all = $total_dppo + $total_rso + $total_po + $total_incentive_expend + $total_expend;

        return Excel::download(new \App\Exports\ExpendAllExport([
            'purchaseOrders' => $purchase_order,
            'debtPaymentPo' => $debtPaymentPo,
            'returSO' => $returSO,
            'incentiveExpend' => $incentiveExpend,
            'expends' => $expend,
            'total_expend_all' => $total_expend_all
        ]), sprintf("%s - %s.xlsx", trans('expend_all.title'), $expend_type));
    }
}

app/Http/Controllers/Report/ProductIdentityController.php
<?php

namespace App\Http\Controllers\Report;

use App\Util\Base\CoreController;
use App\Models\ProductIdentity;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\Category;
use App\Models\Product;
use App\Models\Branch;
use App\Models\Brand;
use App\Models\Stock;
use Excel;

class ProductIdentityController extends CoreController
{
    public function index()
    {
        $brands = Brand::active()->get()->pluck('name','id');
        $branchs = Branch::active()->get()->pluck('name','id');
        $categories = Category::active()->get()->pluck('name','id');
        $products = Product::active()->get()->pluck('name','id');

        if( request('ex') ) {
            return $this->exportExcel();
        }

        return Layout::render('report.product_identity.index', [
            'brands' => $brands,
            'branchs' => $branchs,
            'categories' => $categories,
            'products' => $products
        ]);
    }

    public function exportExcel()
    {
        $operator = Util::get('_sop');
        $operator = is_numeric($operator) ? trans("global.array.operator.$operator") : '';
        $stock = Util::get('_stc');
        $branch_id = Util::get('_bc');

        $query = ProductIdentity::with('product', 'branch')->orderBy('product_id');

        if ($branch_id) {
            $query->where('branch_id', $branch_id);
        }

        if (!empty($operator) && is_numeric($stock)) {
            $query->where('stock', $operator, $stock);
        }

        if( request('_pid') )
        {
            $query->where('product_id', Util::get('_pid'));
        }

        if( request('_bd') || request('_cg') )
        {
            $brand_id = request('_bd');
            $category_id = request('_cg');

            $query->whereHas('product', function($q) use($brand_id, $category_id) {
                if ($brand_id) {
                    $q->where('brand_id', $brand_id);
                }

                if ($category_id) {
                    $q->where('category_id', $category_id);
                }
            });
        }

        $products = $query->get();
        // dd($products->toArray());
        $products = $products->sortBy('product.name');

        return Excel::download(new \App\Exports\ProductIdentityExport($products), trans('product.label.product_identity') . '.xlsx');
    }
}

resources/views/report/supplier_tax/export.blade.php
@php
use App\Util\Helpers\Util;
@endphp

<table>
    <thead>
    <tr>
        <th><b>@lang('product.label.code')</b></th>
        <th><b>@lang('product.label.name')</b></th>
        <th><b>@lang('product.label.branch_id')</b></th>
        <th><b>@lang('product.label.category_id')</b></th>
        <th><b>@lang('product.label.brand_id')</b></th>
        <th><b>@lang('product.label.product_identity')</b></th>
        <th><b>@lang('product.label.gross_profit')</b></th>
        <th><b>@lang('product.label.net_profit')</b></th>
        <th><b>@lang('product.label.tax')</b></th>
    </tr>
    </thead>
    <tbody>
        @php
            $total_tax = 0;
        @endphp
    @foreach($products as $row)
    @php
        $productIdentity = $row->productIdentity;
    @endphp
        <tr>
            <td>{{ $productIdentity->product->code }}</td>
            <td>{{ $productIdentity->product->name }}</td>
            <td>{{ $productIdentity->branch->name }}</td>
            <td>{{ $productIdentity->product->category->name }}</td>
            <td>{{ $productIdentity->product->brand->name }}</td>
            <td>{{ $productIdentity->identity }}</td>
            <td data-format="#,##0_-">{{ $row->gross_profit }}</td>
            @php
                $net_profit = $row->gross_profit - $row->capital_price;
                $tax = $net_profit * 25 / 100;
                $total_tax += $tax;
            @endphp
            <td data-format="#,##0_-">{{ $net_profit }}</td>
            <td data-format="#,##0_-">{{ $tax }}</td>
        </tr>
    @endforeach
    </tbody>
    <thead>
        <tr>
            <td colspan="8"><b>@lang('global.total')</b></td>
            <td data-format="#,##0_-">{{ $total_tax }}</td>
        </tr>
    </thead>
</table>

resources/views/report/supplier_tax/index.blade.php
@extends('layouts.admin')

@inject('util', 'App\Util\Helpers\Util')

@section('content')
<form role="form" action="{{ route('report.supplier.tax.index') }}">
<input type="hidden" name="ex" value="1" />
<div class="row">
    <div class="col-lg-6">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">@lang('global.report') @lang('purchase_order.title')</h3>
            </div>
            <!-- form start -->

            <div class="card-body">
                <div class="form-group">
                    <label for="date">@lang('purchase_order.label.date')</label>
                    <input type="text" name="_dt" class="form-control datetime-rangepicker" placeholder="@lang('purchase_order.placeholder.date')" autocomplete="off">
                </div>

                @if (empty(config('default.bank_id')))
                <div class="form-group">
                    <label for="_bk">@lang('purchase_order.label.bank_id')</label>
                    <select name="_bk"  class="form-control select2" data-placeholder="" style="width: 100%;">
                        <option value=""></option>
                        @foreach ($banks as $id => $name)
                        <option value="{{ $id }}">{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
                @endif

                <div class="form-group">
                    <label for="_bc">@lang('purchase_order.label.branch_id')</label>
                    <select name="_bc"  class="form-control select2" data-placeholder="" style="width: 100%;">
                        <option value=""></option>
                        @foreach ($branchs as $id => $name)
                        <option value="{{ $id }}">{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="_sp">@lang('purchase_order.label.supplier_id')</label>
                    <select name="_sp"  class="form-control select2" data-placeholder="" style="width: 100%;">
                        <option value=""></option>
                        @foreach ($suppliers as $id => $name)
                        <option value="{{ $id }}">{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <a href="{{ route('report.supplier.tax.index') }}" class="btn btn-danger btn-loader">@lang('global.cancel')</a>
                <button type="submit" class="btn btn-success float-right">
                    @lang('global.export')
                </button>
            </div>
        </div>
    </div>
</div>
</form>
@stop