routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login','Auth\LoginController@index')->name('login');
Route::post('login','Auth\LoginController@login')->name('login');
Route::get('logout','Auth\LoginController@logout')->name('logout');

Route::middleware(['web','auth'])->group(function () {
    Route::get('/','DashboardController@index')->name('dashboard');

    Route::middleware(['check.permission'])->group(function () {
        /**
        * Setting
        * */ 
        Route::name('setting.')->prefix('setting')->group(function () {
            Route::name('role.')->prefix('role')->group(function(){
                Route::resource('', 'Setting\RoleController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
    
                Route::post('access','Setting\RoleController@access')->name('access');
            });
    
            Route::resource('permission','Setting\PermissionController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('permission');
    
            Route::name('user.')->prefix('user')->group(function(){
                Route::resource('', 'Setting\UserController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
    
                Route::get('{id}/change-status/{status}','Setting\UserController@change_status')->name('change.status');
            });
    
            // Route::resource('user-api','Setting\UserApiController')->only([
            //     'index', 'edit', 'store', 'destroy'
            // ])->names('user_api');
    
            // Route::resource('domain','Setting\DomainController')->only([
            //     'index', 'edit', 'store', 'destroy'
            // ])->names('domain');
    
            Route::resource('menu','Setting\MenuController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('menu');
    
            Route::resource('setting','Setting\SettingController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('setting');
        });
    
        /**
        * Master
        * */ 
        Route::name('master.')->prefix('master')->group(function () {
            Route::resource('brand','Master\BrandController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('brand');
    
            Route::resource('category','Master\CategoryController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('category');
    
            Route::resource('bank','Master\BankController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('bank');
    
            Route::resource('employee','Master\EmployeeController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('employee');
    
            Route::resource('branch','Master\BranchController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('branch');
    
            Route::resource('member','Master\MemberController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('member');
    
            Route::resource('supplier','Master\SupplierController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('supplier');
    
            Route::name('product.')->prefix('product')->group(function(){
                Route::post('upload','Master\ProductController@upload')->name('upload');
                Route::delete('upload','Master\ProductController@upload')->name('upload');
                
                Route::resource('', 'Master\ProductController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
    
            Route::name('product.identity.')->prefix('product-identity')->group(function(){
                Route::resource('', 'Master\ProductIdentityController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index'
                ]);
            });
    
            Route::name('promo.')->prefix('promo')->group(function(){
                Route::post('upload','Master\PromoController@upload')->name('upload');
                Route::delete('upload','Master\PromoController@upload')->name('upload');
                
                Route::resource('', 'Master\PromoController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
        });
    
        /**
        * Finance
        * */ 
        Route::name('finance.')->prefix('finance')->group(function () {
            Route::resource('category-expend','Finance\CategoryExpendController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('category.expend');
    
            Route::resource('incentive','Finance\IncentiveController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('incentive');
    
            Route::name('expend.')->prefix('expend')->group(function(){
                Route::post('upload','Finance\ExpendController@upload')->name('upload');
                Route::delete('upload','Finance\ExpendController@upload')->name('upload');
                
                Route::resource('', 'Finance\ExpendController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('debt.payment.po.')->prefix('debt-payment-po')->group(function(){
                Route::post('upload','Finance\DebtPaymentPOController@upload')->name('upload');
                Route::delete('upload','Finance\DebtPaymentPOController@upload')->name('upload');
                
                Route::resource('', 'Finance\DebtPaymentPOController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
    
            Route::name('debt.payment.so.')->prefix('debt-payment-so')->group(function(){
                Route::post('upload','Finance\DebtPaymentSOController@upload')->name('upload');
                Route::delete('upload','Finance\DebtPaymentSOController@upload')->name('upload');
                
                Route::resource('', 'Finance\DebtPaymentSOController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
        });
    
        /**
        * Transaction
        * */ 
        Route::name('transaction.')->prefix('transaction')->group(function () {
            Route::name('purchase.order.')->prefix('purchase-order')->group(function(){
                Route::post('upload','Transaction\PurchaseOrderController@upload')->name('upload');
                Route::delete('upload','Transaction\PurchaseOrderController@upload')->name('upload');
                
                Route::resource('', 'Transaction\PurchaseOrderController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('retur.purchase.order.')->prefix('retur-purchase-order')
            ->group(function(){
                Route::post('upload','Transaction\ReturPurchaseOrderController@upload')
                    ->name('upload');
                Route::delete('upload','Transaction\ReturPurchaseOrderController@upload')
                    ->name('upload');
                
                Route::resource('', 'Transaction\ReturPurchaseOrderController',[
                    'parameters' => [
                        '' => 'id',
                    ]
                ])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('sales.order.')->prefix('sales-order')->group(function(){
                Route::post('upload','Transaction\SalesOrderController@upload')->name('upload');
                Route::delete('upload','Transaction\SalesOrderController@upload')->name('upload');
                Route::any('{id}/print-small','Transaction\SalesOrderController@printSmall')->name('note.small');
                
                Route::resource('', 'Transaction\SalesOrderController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('retur.sales.order.')->prefix('retur-sales-order')
            ->group(function(){
                Route::post('upload','Transaction\ReturSalesOrderController@upload')

app/Http/Controllers/Setting/MenuController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Util\Base\CoreController;
use App\Util\Helpers\Util;
use App\Models\Permission;
use App\Models\Menu;

class MenuController extends CoreController
{
    public function index()
    {
        $query = Menu::with('submenu')->firstParents()->orderBy('order','ASC');

        if( request('name') )
        {
            $query->whereLike('name', Util::get('name'));
        }

        if( request('url') )
        {
            $query->whereLike('url', Util::get('url'));
        }

        if( request('route') )
        {
            $query->whereLike('route', Util::get('route'));
        }

        $menus = $query->get();
        $parents = Menu::parents()->get()->pluck('name','id')->toArray();
        
        return $this->render('setting.menu.index', [
            "menus" => $menus,
            "parents" => $parents,
            'breadcrumbs' => [
                [
                    'text' => trans('global.menu.setting'),
                    'url' => '#'
                ],
                [
                    'text' => trans('menu.title'),
                    'url' => route('setting.menu.index')
                ]
            ],
        ]);
    }

    public function edit($id)
    {
        $menu = Menu::find($id);
        $menu = $menu ? $menu->toArray() : [];

        return response()->json([
            'url_edit' => route('setting.menu.update', $id),
            'menu' => $menu,
        ]);
    }

    public function store()
    {
        return $this->store_save();
    }

    public function update($id)
    {
        return $this->store_save($id);
    }

    private function store_save($id =null)
    {
        $result = [
            'status' => FALSE,
            'error' => []
        ];
        $input = request()->except(["_token"]);

        if(array_key_exists('ordering', $input))
        {
            $this->update_order(json_decode($input['ordering'], TRUE));
            $result['status'] = TRUE;
        }
        else
        {
            if(request('is_parent'))
            {
                $input['is_parent'] = $input['is_parent'] == "on" ? 1 : 0;
            }
            else
            {
                $input['is_parent'] = 0;
            }

            $query = Menu::query();

            $input['url'] = '';
            if( \Route::has($input['route']) )
            {
                $input['url'] = str_replace(url('/') . '/', '', route($input['route']));
            }

            $result = $this->save($query, $input,[
                "rules" => [
                    "name" => 'required|max:255',
                    // "url" => 'required|max:100',
                    // "route" => 'required|max:100',
                ],
                "messages" => trans("menu.errors"),
            ]);
        }

        $redirect = redirect()->route('setting.menu.index');        
        if( $result['status'] )
        {
            $redirect->with('success', sprintf('%s', trans("global.success_save")) );
        }
        else
        {
            $redirect->withInput( request()->except(['_token']) )
                        ->withErrors($result['error'])
                        ->with('error', sprintf('%s', trans("global.failed_save")) );
        }

        return $redirect;
    }

    private function update_order($menus, $parent_id = null)
    {
        foreach ($menus as $key => $value)
        {   
            $data = [
                'order' => $key,
                'parent_id' => NULL,
                'is_parent' => 0
            ];

            if(!empty($parent_id))
            {
                $data['parent_id'] = $parent_id;
            } elseif (empty($parent_id)) {
                $data['is_parent'] = 1;
            }

            if( array_key_exists('children', $value) )
            {
                $data['is_parent'] = 1;
                $this->update_order($value['children'], $value['id']);
            }

            Menu::where('id', $value['id'])->update($data);
        }
    }

    public function destroy($id)
    {
        \DB::beginTransaction();
        $row = Menu::find($id);
        $row->permissions()->detach();
        $name = $row->name;

        $status = $this->delete($row, 'soft');

        if($status["status"]){
            session()->flash('success', sprintf("%s %s : %s", trans("global.success_delete"), trans("menu.title"), $name) );
            \DB::commit();
        }else{
            session()->flash('error', sprintf("%s %s : %s", trans("global.failed_delete"), trans("menu.title"), $name) );
            \DB::rollback();
        }
        
        return response()->json( ["status" => $status["status"]] );
    }
}

app/Http/Controllers/Setting/SettingController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Util\Base\CoreController;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\Setting;
use App\Models\Menu;

class SettingController extends CoreController
{
    public function index()
    {
        $query = Setting::orderBy('updated_at','DESC');

        if( request('search_name') )
        {
            $query->whereLike('name', Util::get('search_name'));
        }

        $settings = $query->paginate(Layout::ROW_PER_PAGE)
                            ->appends( request()->except(["page"]) );

        return Layout::render('setting.setting.index', [
            "settings" => $settings
        ]);
    }

    public function edit($id)
    {
        $setting = Setting::find($id);

        return response()->json([
            'url_edit' => route('setting.setting.update', $id),
            'data' => $setting
        ]);
    }

    public function store()
    {
        return $this->store_update();
    }
    
    public function update($id)
    {
        return $this->store_update($id);
    }

    private function store_update($id = null) 
    {
        $input = request()->except(["_token"]);
        $input['status'] = $input['status'] == "on" ? Setting::STATUS_ACTIVE : Setting::STATUS_DEACTIVE;
        if ($input['type'] == Setting::TYPE_NUMBER) {
            $input['value'] = Util::remove_format_currency($input['value_number']);
        }
        
        $redirect = redirect()->back();
        $query = Setting::query();

        $result = $this->save($query, $input,[
            "rules" => [
                "name" => 'required|max:255',
                "key" => 'required|max:255|unique:setting,key,'.($input['id'] ?: 'NULL') .',id',
                "value" => 'required',
            ],
            "messages" => trans("setting.errors"),
            'remove' => ['value_number']
        ]);

        if( $result['status'] )
        {
            $redirect->with('success', sprintf('%s', trans("global.success_save")) );
        }
        else
        {
            $redirect->withInput( request()->except(['_token']) )
                        ->withErrors($result['error'])
                        ->with('error', sprintf('%s', trans("global.failed_save")) );
        }

        return $redirect;
    }

    public function destroy($id)
    {
        \DB::beginTransaction();
        $row = Setting::find($id);
        $name = $row->name;

        $status = $this->delete($row, 'soft');

        if($status["status"]){
            session()->flash('success', sprintf("%s %s : %s", trans("global.success_delete"), trans("setting.title"), $name) );
            \DB::commit();
        }else{
            session()->flash('error', sprintf("%s %s : %s", trans("global.failed_delete"), trans("setting.title"), $name) );
            \DB::rollback();
        }
        
        return response()->json( ["status" => $status["status"]] );
    }
}

resources/views/setting/permission/form.blade.php
<!-- form start -->
<form id="form-permission" role="form" method="POST" action="{{ route('setting.permission.store') }}">
    @csrf
    <input type="hidden" name="id" value="{{ old('id') }}">
    <div class="card-body">
        <div class="form-group">
            <label for="name">@lang('permission.label.name')</label>
            <input type="text" name="name" class="form-control @classInpError('name')" placeholder="@lang('permission.placeholder.name')" value="{{ old('name') }}">
            
            @inpSpanError(['column'=>'name'])
        </div>
        <div class="form-group">
            <label for="slug">@lang('permission.label.slug')</label>
            <input type="text" name="slug" class="form-control @classInpError('slug')" placeholder="@lang('permission.placeholder.slug')" value="{{ old('slug') }}">

            @inpSpanError(['column'=>'slug'])
        </div>
        <div class="form-group">
            <label for="icon">@lang('permission.label.description')</label>
            <textarea name="description" class="form-control @classInpError('description')" rows="3" placeholder="@lang('permission.placeholder.description')" >{{ old('description') }}</textarea>

            @inpSpanError(['column'=>'description'])
        </div>
        
        <div class="form-group">
            <label for="menu">@lang('permission.label.menu')</label>
            <select name="menu"  id="permission-menu" class="form-control select2 @classInpError('menu')" data-placeholder="" style="width: 100%;">
                <option value=""></option>
                @foreach ($menus as $id => $name)
                <option value="{{ $id }}" {{ old('menu') == $id ? "selected"  : ""}}>{{ $name }}</option>
                @endforeach
            </select>
            @inpSpanError(['column'=>'menu'])
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <a href="{{ route('setting.permission.index') }}" class="btn btn-danger btn-loader">@lang('global.cancel')</a>
        <button type="submit" class="btn btn-success float-right btn-loader">@lang('global.save')</button>
    </div>
</form>

resources/views/setting/permission/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">@lang('global.search') @lang('permission.title')</h3>
            </div>
            <!-- /.card-header -->
            @include( $template . 'setting.permission.search')
        </div>
    </div>
</div>
<div class="row" id="content-permission">
    <div class="col-xs-12 xol-sm-12 col-lg-8">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title"> @lang('global.list') @lang('permission.title')</h3>
            </div>
            <div class="card-body table-responsive p-0" style="height: 500px;">
                <table class="table table-head-fixed sorting-table" data-form="form-search-permission">
                    <thead>
                        <tr>
                            <th style="width: 5%;" class="text-center">@lang('global.no')</th>
                            <th style="width: 35%;" class="sorting-form" data-column="name">@lang('permission.label.name')</th>
                            <th style="width: 25%;" class="sorting-form" data-column="slug">@lang('permission.label.slug')</th>
                            <th style="width: 20%;" class="text-center">@lang('permission.label.menu')</th>
                            <th style="width: 15%;">@lang('global.action')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if( isset($permissions) && count($permissions) > 0 )
                        @foreach( $permissions as $i => $r)
                        <tr>
                            <td class="text-center">{{ $permissions->firstItem() + $i }}</td>
                            <td class="text-wrap">{{ $r->name }}</td>
                            <td class="text-wrap">{{ $r->slug }}</td>
                            <td class="text-center text-wrap">
                                {{ $r->menus->count() > 0 ? $r->menus->first()->name : '-' }}
                            </td>
                            <td class="">
                                <div class="btn-group">
                                    @hasPermission('setting.permission.edit')
                                    <a title="@lang('global.edit')" href="javascript:void(0)" data-href="{{ route('setting.permission.edit', $r['id']) }}" class="btn btn-sm btn-warning btn-edit-permission btn-loader" data-toggle="tooltip">
                                        <i class="fas fa-edit m-0"></i>
                                    </a>
                                    @endhasPermission

                                    @hasPermission('setting.permission.destroy')
                                    <button title="@lang('global.delete')" data-href="{{ route('setting.permission.destroy', $r['id']) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip">
                                        <i class="fa fa-trash m-0"></i>
                                    </button>
                                    @endhasPermission
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="5" class="text-center">@lang('global.data_not_available')</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            @if( isset($permissions) && count($permissions) > 0 )
            {!! \App\Util\Base\Layout::paging($permissions) !!}
            @endif
        </div>
    </div>
    
    <div class="col-xs-12 xol-sm-12 col-lg-4">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">@lang('global.form') @lang('permission.title')</h3>
            </div>
            <!-- /.card-header -->
            @include( $template . 'setting.permission.form')
        </div>
    </div>
</div>
@stop

@push('js')
    <script type="text/javascript" src="{{ asset('js/admin/setting/permission.js') }}?{{ config('app.version') }}"></script>
@endpush

resources/views/setting/permission/search.blade.php
<!-- form start -->
<form role="form" id="form-search-permission" action="{{ route('setting.permission.index') }}">
    <div class="card-body">
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label for="name">@lang('permission.label.name')</label>
                    <input type="text" name="_nm" class="form-control" placeholder="@lang('permission.placeholder.name')" value="{{ request('_nm') }}">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="slug">@lang('permission.label.slug')</label>
                    <input type="text" name="_sg" class="form-control" placeholder="@lang('permission.placeholder.slug')" value="{{ request('_sg') }}">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="_mn">@lang('permission.label.menu')</label>
                    <select name="_mn"  class="form-control select2" data-placeholder="" style="width: 100%;">
                        <option value=""></option>
                        @foreach ($menus as $id => $name)
                        <option value="{{ $id }}" {{ request('_mn') == $id ? "selected"  : ""}}>{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <a href="{{ route('setting.permission.index') }}" class="btn btn-info btn-loader">@lang('global.show_all')</a>
        <button type="submit" class="btn btn-success btn-loader">
            @lang('global.search')
        </button>
    </div>
</form>