routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login','Auth\LoginController@index')->name('login');
Route::post('login','Auth\LoginController@login')->name('login');
Route::get('logout','Auth\LoginController@logout')->name('logout');

Route::middleware(['web','auth'])->group(function () {
    Route::get('/','DashboardController@index')->name('dashboard');

    Route::middleware(['check.permission'])->group(function () {
        /**
        * Setting
        * */ 
        Route::name('setting.')->prefix('setting')->group(function () {
            Route::name('role.')->prefix('role')->group(function(){
                Route::resource('', 'Setting\RoleController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
    
                Route::post('access','Setting\RoleController@access')->name('access');
            });
    
            Route::resource('permission','Setting\PermissionController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('permission');
    
            Route::name('user.')->prefix('user')->group(function(){
                Route::resource('', 'Setting\UserController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
    
                Route::get('{id}/change-status/{status}','Setting\UserController@change_status')->name('change.status');
            });
    
            // Route::resource('user-api','Setting\UserApiController')->only([
            //     'index', 'edit', 'store', 'destroy'
            // ])->names('user_api');
    
            // Route::resource('domain','Setting\DomainController')->only([
            //     'index', 'edit', 'store', 'destroy'
            // ])->names('domain');
    
            Route::resource('menu','Setting\MenuController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('menu');
    
            Route::resource('setting','Setting\SettingController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('setting');
        });
    
        /**
        * Master
        * */ 
        Route::name('master.')->prefix('master')->group(function () {
            Route::resource('brand','Master\BrandController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('brand');
    
            Route::resource('category','Master\CategoryController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('category');
    
            Route::resource('bank','Master\BankController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('bank');
    
            Route::resource('employee','Master\EmployeeController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('employee');
    
            Route::resource('branch','Master\BranchController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('branch');
    
            Route::resource('member','Master\MemberController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('member');
    
            Route::resource('supplier','Master\SupplierController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('supplier');
    
            Route::name('product.')->prefix('product')->group(function(){
                Route::post('upload','Master\ProductController@upload')->name('upload');
                Route::delete('upload','Master\ProductController@upload')->name('upload');
                
                Route::resource('', 'Master\ProductController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
    
            Route::name('product.identity.')->prefix('product-identity')->group(function(){
                Route::resource('', 'Master\ProductIdentityController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index'
                ]);
            });
    
            Route::name('promo.')->prefix('promo')->group(function(){
                Route::post('upload','Master\PromoController@upload')->name('upload');
                Route::delete('upload','Master\PromoController@upload')->name('upload');
                
                Route::resource('', 'Master\PromoController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
        });
    
        /**
        * Finance
        * */ 
        Route::name('finance.')->prefix('finance')->group(function () {
            Route::resource('category-expend','Finance\CategoryExpendController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('category.expend');
    
            Route::resource('incentive','Finance\IncentiveController')->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ])->names('incentive');
    
            Route::name('expend.')->prefix('expend')->group(function(){
                Route::post('upload','Finance\ExpendController@upload')->name('upload');
                Route::delete('upload','Finance\ExpendController@upload')->name('upload');
                
                Route::resource('', 'Finance\ExpendController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('debt.payment.po.')->prefix('debt-payment-po')->group(function(){
                Route::post('upload','Finance\DebtPaymentPOController@upload')->name('upload');
                Route::delete('upload','Finance\DebtPaymentPOController@upload')->name('upload');
                
                Route::resource('', 'Finance\DebtPaymentPOController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
    
            Route::name('debt.payment.so.')->prefix('debt-payment-so')->group(function(){
                Route::post('upload','Finance\DebtPaymentSOController@upload')->name('upload');
                Route::delete('upload','Finance\DebtPaymentSOController@upload')->name('upload');
                
                Route::resource('', 'Finance\DebtPaymentSOController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
                ]);
            });
        });
    
        /**
        * Transaction
        * */ 
        Route::name('transaction.')->prefix('transaction')->group(function () {
            Route::name('purchase.order.')->prefix('purchase-order')->group(function(){
                Route::post('upload','Transaction\PurchaseOrderController@upload')->name('upload');
                Route::delete('upload','Transaction\PurchaseOrderController@upload')->name('upload');
                
                Route::resource('', 'Transaction\PurchaseOrderController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('retur.purchase.order.')->prefix('retur-purchase-order')
            ->group(function(){
                Route::post('upload','Transaction\ReturPurchaseOrderController@upload')
                    ->name('upload');
                Route::delete('upload','Transaction\ReturPurchaseOrderController@upload')
                    ->name('upload');
                
                Route::resource('', 'Transaction\ReturPurchaseOrderController',[
                    'parameters' => [
                        '' => 'id',
                    ]
                ])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('sales.order.')->prefix('sales-order')->group(function(){
                Route::post('upload','Transaction\SalesOrderController@upload')->name('upload');
                Route::delete('upload','Transaction\SalesOrderController@upload')->name('upload');
                Route::any('{id}/print-small','Transaction\SalesOrderController@printSmall')->name('note.small');
                
                Route::resource('', 'Transaction\SalesOrderController',['parameters' => [
                    '' => 'id',
                ]])->only([
                    'index', 'show', 'edit', 'create', 'store', 'update', 'destroy'
                ]);
            });
    
            Route::name('retur.sales.order.')->prefix('retur-sales-order')
            ->group(function(){
                Route::post('upload','Transaction\ReturSalesOrderController@upload')

app/Http/Controllers/Master/BankController.php
<?php

namespace App\Http\Controllers\Master;

use Illuminate\Validation\Rule;

use App\Util\Base\CoreController;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\Bank;

class BankController extends CoreController
{
    public function index()
    {
        $query = Bank::query();

        $orderBy = Util::get('_s_ob');
        $sorting = Util::get('_s_s');
        $sorting = empty($sorting) ? 0 : $sorting;
        if (!empty($orderBy) && $orderBy != 'stock') {
            $query->orderBy($orderBy, trans("global.array.sorting.$sorting"));
        } else {
            $query->orderBy('updated_at','DESC');
        }

        if( request('search_name') )
        {
            $query->whereLike('name', Util::get('search_name'));
        }

        if( request('_an') )
        {
            $query->whereLike('account_number', Util::get('_an'));
        }

        if( request('_nmow') )
        {
            $query->whereLike('name_owner', Util::get('_nmow'));
        }

        if( is_numeric(request('_sts')) )
        {
            $query->status(Util::get('_sts'));
        }

        if( is_numeric(request('_df')) )
        {
            $query->default(Util::get('_df'));
        }

        $banks = $query->paginate(Layout::ROW_PER_PAGE)->appends( request()->except(["page"]) );

        return Layout::render('master.bank.index', [
            "banks" => $banks,
            'breadcrumbs' => [
                [
                    'text' => trans('global.menu.bank'),
                    'url' => '#'
                ],
                [
                    'text' => trans('bank.title'),
                    'url' => route('master.bank.index')
                ]
            ],
        ]);
    }

    public function edit($id)
    {
        $bank = Bank::find($id);
        $bank = $bank ? $bank->toArray() : [];

        return response()->json([
            'url_edit' => route('master.bank.update', $id),
            'data' => $bank
        ]);
    }

    public function store()
    {
        return $this->store_update();
    }
    
    public function update($id)
    {
        return $this->store_update($id);
    }

    private function store_update($id = null) 
    {
        $input = request()->except(["_token"]);
        $input['status'] = $input['status'] == 'on' ? Bank::STATUS_ACTIVE : Bank::STATUS_DEACTIVE;
        $input['is_default'] = $input['is_default'] == 'on' ? Bank::DEFAULT_YES : Bank::DEFAULT_NO;

        $redirect = redirect()->back();
        $query = Bank::query();

        $rule_default = '';
        if ($input['is_default']) {
            $rule_default = 'unique:bank,is_default,'.($input['id'] ?: 'NULL') .',id';
        }

        $result = $this->save($query, $input,[
            "rules" => [
                "name" => 'required|max:255',
                'account_number' => 'numeric|unique:bank,account_number,'.($input['id'] ?: 'NULL') .',id',
                'is_default' => $rule_default,
                'status' => $input['is_default'] ? Rule::in([1]) : ''
            ],
            "messages" => trans("bank.errors"),
        ]);

        if( $result['status'] )
        {
            $redirect->with('success', sprintf('%s', trans("global.success_save")) );
        }
        else
        {
            $redirect->withInput( request()->except(['_token']) )
                        ->withErrors($result['error'])
                        ->with('error', sprintf('%s', trans("global.failed_save")) );
        }

        return $redirect;
    }

    public function destroy($id)
    {
        \DB::beginTransaction();
        $row = Bank::find($id);
        $name = $row->name;

        $status = $this->delete($row, 'soft');
        if($status["status"]){
            session()->flash('success', sprintf("%s %s : %s", trans("global.success_delete"), trans("bank.title"), $name) );
            \DB::commit();
        }else{
            session()->flash('error', sprintf("%s %s : %s", trans("global.failed_delete"), trans("bank.title"), $name) );
            \DB::rollback();
        }
        
        return response()->json( ["status" => $status["status"]] );
    }

    public function ajaxBank()
    {
        $params = request()->all();

        $list = Bank::select("id","name as text")
                        ->whereLike("name", $params["query"])
                        ->get()
                        ->toArray();

        return response()->json([
            "items" => $list,
            "count" => count($list)
        ]);
    }
}

app/Http/Controllers/Master/ProductIdentityController.php
<?php

namespace App\Http\Controllers\Master;

use App\Util\Base\CoreController;
use App\Models\ProductIdentity;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\Category;
use App\Models\Product;
use App\Models\Branch;
use App\Models\Brand;
use App\Models\Promo;
use App\Models\Stock;

class ProductIdentityController extends CoreController
{
    public function index()
    {
        $query = ProductIdentity::with([
            'branch', 'poDetail',
            'product' => function($q) {
                $q->with('category', 'brand');
            }
        ]);

        $operator = Util::get('_sop');
        $operator = is_numeric($operator) ? trans("global.array.operator.$operator") : '';
        $stock = Util::get('_stc') ?? 0;
        $branch_id = Util::get('_bc');
        
        if (!empty($operator) || is_numeric($stock)) {
            $query->where('stock', $operator, $stock);
        }

        if (!empty($branch_id)) {
            $query->where('branch_id', $branch_id);
        }

        if( request('_k') )
        {
            $keyword = Util::get('_k');
            $query->where(function($q) use ($keyword) {
                $q->whereHas('product', function($q1) use ($keyword) {
                    $q1->whereLike('name', $keyword)
                        ->orWhereLike('code', $keyword);
                })->orWhere(function($q1) use ($keyword) {
                    $q1->whereLike('identity', $keyword);
                });
            });
        }

        if( request('_bd') || request('_cg') )
        {
            $brand_id = Util::get('_bd');
            $category_id = Util::get('_cg');

            $query->whereHas('product', function($q) use($brand_id, $category_id) {
                if ($brand_id) {
                    $q->where('brand_id', $brand_id);
                }

                if ($category_id) {
                    $q->where('category_id', $category_id);
                }
            });
        }

        $orderBy = Util::get('_s_ob');
        $sorting = Util::get('_s_s');
        $sorting = empty($sorting) ? 0 : $sorting;
        if (!empty($orderBy)) {
            $query->orderBy($orderBy, trans("global.array.sorting.$sorting"));
        } else if(empty($orderBy)) {
            $query->orderBy('updated_at', 'DESC');
        }

        $products = $query->paginate(Layout::ROW_PER_PAGE)
                        ->appends( request()->except(["page"]) );
        
        $brands = Brand::active()->get()->pluck('name','id');
        $branchs = Branch::active()->get()->pluck('name','id');
        $categories = Category::active()->get()->pluck('name','id');

        return Layout::render('master.product_identity.index', [
            "products" => $products,
            'brands' => $brands,
            'branchs' => $branchs,
            'categories' => $categories,
        ]);
    }
}

resources/views/master/member/form.blade.php
<!-- form start -->
<form id="form-member" role="form" method="POST" action="{{ route('master.member.store') }}">
    @csrf
    <input type="hidden" name="id" value="{{ old('id') }}">
    <div class="card-body">
        <div class="form-group">
            <label for="name">@lang('member.label.name')</label>
            <input type="text" name="name" class="form-control @classInpError('name')" placeholder="@lang('member.placeholder.name')" value="{{ old('name') }}">
            
            @inpSpanError(['column'=>'name'])
        </div>
        <div class="form-group">
            <label for="phone">@lang('member.label.phone')</label>
            <input type="text" name="phone" class="form-control @classInpError('phone')" placeholder="@lang('member.placeholder.phone')" value="{{ old('phone') }}">
            
            @inpSpanError(['column'=>'phone'])
        </div>
        <div class="form-group">
            <label for="address">@lang('member.label.address')</label>
            <textarea name="address" class="form-control @classInpError('address')" rows="3" placeholder="@lang('member.placeholder.address')" >{{ old('address') }}</textarea>
            
            @inpSpanError(['column'=>'address'])
        </div>
        <div class="form-group">
            <label for="form-identity_type" class="control-label">@lang('member.label.identity_type')</label>
            <select name="identity_type" id="form-identity_type" class="form-control select2 @classInpError('identity_type')" data-placeholder="">
                @foreach(trans('member.list.identity_type') as $id => $name)
                    <option value="{{ $id }}" {{ old('identity_type') == $id ? "selected"  : ""}} >
                        {{ $name }}
                    </option>
                @endforeach
            </select>

            @inpSpanError(['column'=>'identity_type'])
        </div>
        <div class="form-group">
            <label for="identity">@lang('member.label.identity')</label>
            <input type="text" name="identity" class="form-control @classInpError('identity')" placeholder="@lang('member.placeholder.identity')" value="{{ old('identity') }}">
            
            @inpSpanError(['column'=>'identity'])
        </div>
        <div class="form-group">
            <label for="birthdate">@lang('member.label.birthdate')</label>
            <input type="text" name="birthdate" class="form-control datepicker @classInpError('birthdate')" placeholder="@lang('member.placeholder.birthdate')" autocomplete="off" value="{{ old('birthdate') }}">
            
            @inpSpanError(['column'=>'birthdate'])
        </div>
        <div class="form-group">
            <label for="member_number">@lang('member.label.member_number')</label>
            <input type="text" name="member_number" class="form-control @classInpError('member_number')" placeholder="@lang('member.placeholder.member_number')" value="{{ old('member_number') ?: $model->nextNumber() }}">
            
            @inpSpanError(['column'=>'member_number'])
        </div>

        <div class="form-group">
            <label for="form-type" class="control-label">@lang('member.label.type')</label>
            <select name="type" id="form-type" class="form-control select2 @classInpError('type')" data-placeholder="">
                @foreach(trans('member.list.type') as $id => $name)
                    <option value="{{ $id }}" {{ old('type') == $id ? "selected"  : ""}} >
                        {{ $name }}
                    </option>
                @endforeach
            </select>

            @inpSpanError(['column'=>'type'])
        </div>

        {{--
        <div class="form-group">
            <label for="max_day_debt">@lang('member.label.max_day_debt')</label>
            <input type="text" name="max_day_debt" class="form-control @classInpError('max_day_debt')" placeholder="@lang('member.placeholder.max_day_debt')" value="{{ old('max_day_debt') }}">
            
            @inpSpanError(['column'=>'max_day_debt'])
        </div>
        <div class="form-group">
            <label for="max_debt">@lang('member.label.max_debt')</label>
            <input type="text" name="max_debt" class="form-control format-number @classInpError('max_debt')" placeholder="@lang('member.placeholder.max_debt')" value="{{ old('max_debt') }}">
            
            @inpSpanError(['column'=>'max_debt'])
        </div>
        --}}
        
        <div class="form-group">
            <div class="custom-control custom-switch">
                <input type="hidden" name="status" value="0" />
                <input type="checkbox" class="custom-control-input @classInpError('status')" name="status"  id="member-status" {{ ( old('status') || old('status') == 'on' ) ? 'checked' : '' }}>
                <label class="custom-control-label" for="member-status">@lang('member.label.status')</label>

                <span data-toggle="tooltip" data-placement="top" title="@lang('global.message.desc_status')">
                    <i class="fas fa-question-circle"></i>
                </span>
                @inpSpanError(['column'=>'status'])
            </div>
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <a href="{{ route('master.member.index') }}" class="btn btn-danger btn-loader">@lang('global.cancel')</a>
        <button type="submit" class="btn btn-success float-right btn-loader">@lang('global.save')</button>
    </div>
</form>

resources/views/master/member/search.blade.php
<!-- form start -->
<form role="form" id="form-search-member" action="{{ route('master.member.index') }}">
    <div class="card-body">
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label for="name">@lang('member.label.name')</label>
                    <input type="text" name="_nm" class="form-control" placeholder="@lang('member.placeholder.name')" value="{{ request('_nm') }}">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="_tp">@lang('member.label.type')</label>
                    <select name="_tp"  class="form-control" style="width: 100%;">
                        <option value=""></option>
                        @foreach (trans('member.list.type') as $id => $name)
                        <option value="{{ $id }}" {{ request('_tp') == $id ? "selected"  : ""}}>{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="search_status">@lang('member.label.status')</label>
                    <select name="search_status"  class="form-control" style="width: 100%;">
                        <option value="" selected></option>
                        @foreach (trans('member.list.status') as $id => $name)
                        <option value="{{ $id }}" {{ is_numeric(request('search_status')) && request('search_status') == $id ? "selected"  : ""}}>{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <a href="{{ route('master.member.index') }}" class="btn btn-info btn-loader">@lang('global.show_all')</a>
        <button type="submit" class="btn btn-success btn-loader">
            @lang('global.search')
        </button>
    </div>
</form>